### ISSUE TITLE
Actualizar documentación

### ISSUE THREAD

**Issue by Hellaynea-sideaccount** [Hellaynea/Coursera_Github_HealthChecks#2]
El archivo README todavia utiliza el nombre antiguo del script.
Además la documentación esta bastante vacía, explica un poco mas como funciona.

**Comment by Hellaynea** [comment]
No se ha cerrado directamente porque he escrito "Cierra #2" en lugar de "Close #2", por lo que github no lo reconoce, cierro manualmente
